### ISSUE TITLE
I made a kaktovik numerals sans font, that you can use.

### ISSUE THREAD

**Issue by MY1L** [ChrisUser/kaktovik-converter#14]
### Describe your proposal

 https://github.com/MY1L/Unicode/releases/tag/NotoUni7 It's free. 👉**CtrlMath-1.otf** 
![knum](https://user-images.githubusercontent.com/58043328/218787109-10583d56-fe69-4371-af6a-d8aaafbdb77b.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisUser** [comment]
That's amazing, can you provide me a guide on how to add this typeface to my project?
Unfortunately I can't read chinese so if you can, one in english should be fine.

Or even better: you can download the project, create a new branch and make the changes yourself, then open a pull request and wait for approval. 😉
You don't need to do all the work, just the initial import method of the font will be enough.

**Comment by MY1L** [comment]
Just type these characters e.g., `𝋀𝋁𝋂𝋃𝋄𝋅𝋆𝋇𝋈𝋉𝋊𝋋𝋌𝋍𝋎𝋏𝋐𝋑𝋒𝋓` 
🤔, I made a [digits.png](https://user-images.githubusercontent.com/58043328/219385540-45958630-340b-404f-a051-423b0195c356.png) for replace, how about this? 
![digits](https://user-images.githubusercontent.com/58043328/219385540-45958630-340b-404f-a051-423b0195c356.png)

**Comment by ChrisUser** [comment]
Thanks for taking the time to provide me with the png file. I'll go with this last option as the result is great and didn't change any of the project logics. I'm going to publish this last edit straight away by closing #15.

Thanks again for your contribution, I hope I gave you all the credit you deserve.

Could you tell me one of your **email addresses linked to your GitHub** account? I'd like to list you as a co-author of these changes but I'm not able to do it with the username only.

**Comment by MY1L** [comment]
actually, I rarely use email… but this is also my https://twitter.com/MY1Ltype

**Comment by ChrisUser** [comment]
Since you haven't opened any pull request GitHub doesn't know that you have directly contributed to this project.

I just wanted to list you as a co-author to one of the changes of the pull request connected to this issue to add your profile to this project's contributors. In order to do so i have to add the following to a commit:

```
Co-authored-by: MY1L <your@email.com>
```

It seems that without a valid email address (**connected to the user's GitHub profile**) this message gets completely ignored.

If you prefer not sharing your email for privacy reasons i can skip this part and directly close the pull request associated with this issue.
Let me know if it's okay for you if I close the pull request without adding you as a contributor with the `Co-authored ...` function.

**Comment by MY1L** [comment]
I see, is this 👉 58043328+MY1L@users.noreply.github.com

**Comment by ChrisUser** [comment]
I've added you as a Co-author in the pull request that will be merged as soon as I'll post this comment.

Thanks again for your kind contribution.
